version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./.docker/postgres:/data/postgres
    ports:
      - "5432:5432"